name: AmongMiner
version: 0.0.1
author: Alexzvn
main: dev.alexzvn.among.AmongMiner

api-version: 1.16

depend: [ProtocolLib]

commands:
  amongminer:
    alias: am
    descriptions: Base command

  join:
    descriptions: join to game

  leave:
    descriptions: leave game

permissions:
  amongminer.admin:
    description: Gives access to everything!